### ISSUE TITLE
Error: Cannot find module 'grubbs'

### ISSUE THREAD

**Issue by 0xparashar** [xcatliu/grubbs#1]
I am getting the following error while using it, I have done npm install but still I am getting this error

    Error: Cannot find module 'grubbs'
     at Function.Module._resolveFilename (module.js:469:15)
     at Function.Module._load (module.js:417:25)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/home/ankit/working/kelman.js:7:14)
     at Module._compile (module.js:570:32)
     at Object.Module._extensions..js (module.js:579:10)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3)

**Comment by xcatliu** [comment]
@ankitiitb1069 Thanks for your feedback!
I've updated a new version v1.3.1 to fix this problem.
It should works now.
